// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WbsTool.Api.Data;

#nullable disable

namespace WbsTool.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706102015_Phase2_ERPModules")]
    partial class Phase2_ERPModules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("WbsTool.Api.Modules.Capacity.Models.CapacityAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ActualHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AllocationPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PlannedHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WbsNodeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("WbsNodeId");

                    b.ToTable("CapacityAllocations", (string)null);
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Competencies.Models.Competency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Competencies", (string)null);
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Competencies.Models.PersonCompetency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompetencyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProficiencyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompetencyId");

                    b.HasIndex("PersonId", "CompetencyId")
                        .IsUnique();

                    b.ToTable("PersonCompetencies", (string)null);
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Competencies.Models.WbsRequiredCompetency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompetencyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RequiredLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WbsNodeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompetencyId");

                    b.HasIndex("WbsNodeId");

                    b.HasIndex("ProjectId", "WbsNodeId", "CompetencyId")
                        .IsUnique();

                    b.ToTable("WbsRequiredCompetencies", (string)null);
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Governance.Models.RoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevokedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScopeType")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "Role", "ScopeType", "ProjectId", "IsActive");

                    b.ToTable("RoleAssignments", (string)null);
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Persons.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPlaceholder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlaceholderType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "alle",
                            IsActive = true,
                            IsPlaceholder = true,
                            PlaceholderType = "All",
                            ShortName = "alle",
                            UpdatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Ingenieur",
                            IsActive = true,
                            IsPlaceholder = true,
                            PlaceholderType = "RolePlaceholder",
                            ShortName = "Ingenieur",
                            UpdatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Tobias",
                            Email = "tobias@example.local",
                            IsActive = true,
                            IsPlaceholder = false,
                            ShortName = "Tobias",
                            UpdatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            CreatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Ibrahim",
                            Email = "ibrahim@example.local",
                            IsActive = true,
                            IsPlaceholder = false,
                            ShortName = "Ibrahim",
                            UpdatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            CreatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Dennis",
                            Email = "dennis@example.local",
                            IsActive = true,
                            IsPlaceholder = false,
                            ShortName = "Dennis",
                            UpdatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("WbsTool.Api.Modules.ProcessPhases.Models.ProcessPhase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultResponsibility")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Goal")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ProcessPhases", (string)null);
                });

            modelBuilder.Entity("WbsTool.Api.Modules.ProcessPhases.Models.WbsPhaseMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProcessPhaseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WbsNodeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcessPhaseId");

                    b.HasIndex("WbsNodeId");

                    b.HasIndex("ProjectId", "WbsNodeId", "ProcessPhaseId")
                        .IsUnique();

                    b.ToTable("WbsPhaseMappings", (string)null);
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Projects.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PlannedEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PlannedStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("WbsTool.Api.Modules.RateCategories.Models.RateCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RateCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Code = "A",
                            CreatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EUR",
                            HourlyRate = 120m,
                            IsActive = true,
                            Name = "Kategorie A",
                            UpdatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Code = "B",
                            CreatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EUR",
                            HourlyRate = 95m,
                            IsActive = true,
                            Name = "Kategorie B",
                            UpdatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Code = "C",
                            CreatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EUR",
                            HourlyRate = 75m,
                            IsActive = true,
                            Name = "Kategorie C",
                            UpdatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("WbsTool.Api.Modules.ResourceDemands.Models.ResourceDemand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionComment")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PlannedHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RequiredCompetencyId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StatusChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusChangedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WbsNodeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RequiredCompetencyId");

                    b.HasIndex("WbsNodeId");

                    b.ToTable("ResourceDemands", (string)null);
                });

            modelBuilder.Entity("WbsTool.Api.Modules.TaskStatuses.Models.TaskStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TaskStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "Empty",
                            Color = "#94A3B8",
                            IsActive = true,
                            IsTerminal = false,
                            Label = "leer",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "InCreation",
                            Color = "#F59E0B",
                            IsActive = true,
                            IsTerminal = false,
                            Label = "in Erstellung",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "Delivered",
                            Color = "#3B82F6",
                            IsActive = true,
                            IsTerminal = false,
                            Label = "geliefert",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Code = "Blocked",
                            Color = "#DC2626",
                            IsActive = true,
                            IsTerminal = false,
                            Label = "blockiert",
                            SortOrder = 40
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Code = "Done",
                            Color = "#16A34A",
                            IsActive = true,
                            IsTerminal = true,
                            Label = "abgeschlossen",
                            SortOrder = 50
                        });
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Wbs.Models.ResourceAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ActualHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ActualRateCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignmentRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PlannedHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("PlannedRateCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WbsNodeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActualRateCategoryId");

                    b.HasIndex("PersonId");

                    b.HasIndex("PlannedRateCategoryId");

                    b.HasIndex("WbsNodeId", "PersonId", "AssignmentRole", "IsActive");

                    b.ToTable("ResourceAssignments", (string)null);
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Wbs.Models.WbsNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ActualHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ImportedActualCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ImportedPlannedCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PlannedEnd")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PlannedHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("PlannedStart")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("StatusId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VisibleWbsId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("StatusId");

                    b.HasIndex("ProjectId", "VisibleWbsId")
                        .IsUnique();

                    b.ToTable("WbsNodes", (string)null);
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Capacity.Models.CapacityAllocation", b =>
                {
                    b.HasOne("WbsTool.Api.Modules.Persons.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WbsTool.Api.Modules.Projects.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WbsTool.Api.Modules.Wbs.Models.WbsNode", "WbsNode")
                        .WithMany()
                        .HasForeignKey("WbsNodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Person");

                    b.Navigation("Project");

                    b.Navigation("WbsNode");
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Competencies.Models.PersonCompetency", b =>
                {
                    b.HasOne("WbsTool.Api.Modules.Competencies.Models.Competency", "Competency")
                        .WithMany()
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WbsTool.Api.Modules.Persons.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competency");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Competencies.Models.WbsRequiredCompetency", b =>
                {
                    b.HasOne("WbsTool.Api.Modules.Competencies.Models.Competency", "Competency")
                        .WithMany()
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WbsTool.Api.Modules.Wbs.Models.WbsNode", "WbsNode")
                        .WithMany()
                        .HasForeignKey("WbsNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competency");

                    b.Navigation("WbsNode");
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Governance.Models.RoleAssignment", b =>
                {
                    b.HasOne("WbsTool.Api.Modules.Persons.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("WbsTool.Api.Modules.ProcessPhases.Models.WbsPhaseMapping", b =>
                {
                    b.HasOne("WbsTool.Api.Modules.ProcessPhases.Models.ProcessPhase", "ProcessPhase")
                        .WithMany()
                        .HasForeignKey("ProcessPhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WbsTool.Api.Modules.Wbs.Models.WbsNode", "WbsNode")
                        .WithMany()
                        .HasForeignKey("WbsNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessPhase");

                    b.Navigation("WbsNode");
                });

            modelBuilder.Entity("WbsTool.Api.Modules.ResourceDemands.Models.ResourceDemand", b =>
                {
                    b.HasOne("WbsTool.Api.Modules.Projects.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WbsTool.Api.Modules.Competencies.Models.Competency", "RequiredCompetency")
                        .WithMany()
                        .HasForeignKey("RequiredCompetencyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WbsTool.Api.Modules.Wbs.Models.WbsNode", "WbsNode")
                        .WithMany()
                        .HasForeignKey("WbsNodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");

                    b.Navigation("RequiredCompetency");

                    b.Navigation("WbsNode");
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Wbs.Models.ResourceAssignment", b =>
                {
                    b.HasOne("WbsTool.Api.Modules.RateCategories.Models.RateCategory", "ActualRateCategory")
                        .WithMany("ActualAssignments")
                        .HasForeignKey("ActualRateCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WbsTool.Api.Modules.Persons.Models.Person", "Person")
                        .WithMany("ResourceAssignments")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WbsTool.Api.Modules.RateCategories.Models.RateCategory", "PlannedRateCategory")
                        .WithMany("PlannedAssignments")
                        .HasForeignKey("PlannedRateCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WbsTool.Api.Modules.Wbs.Models.WbsNode", "WbsNode")
                        .WithMany("ResourceAssignments")
                        .HasForeignKey("WbsNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActualRateCategory");

                    b.Navigation("Person");

                    b.Navigation("PlannedRateCategory");

                    b.Navigation("WbsNode");
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Wbs.Models.WbsNode", b =>
                {
                    b.HasOne("WbsTool.Api.Modules.Wbs.Models.WbsNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WbsTool.Api.Modules.Projects.Models.Project", "Project")
                        .WithMany("WbsNodes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WbsTool.Api.Modules.TaskStatuses.Models.TaskStatus", "Status")
                        .WithMany("WbsNodes")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");

                    b.Navigation("Project");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Persons.Models.Person", b =>
                {
                    b.Navigation("ResourceAssignments");
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Projects.Models.Project", b =>
                {
                    b.Navigation("WbsNodes");
                });

            modelBuilder.Entity("WbsTool.Api.Modules.RateCategories.Models.RateCategory", b =>
                {
                    b.Navigation("ActualAssignments");

                    b.Navigation("PlannedAssignments");
                });

            modelBuilder.Entity("WbsTool.Api.Modules.TaskStatuses.Models.TaskStatus", b =>
                {
                    b.Navigation("WbsNodes");
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Wbs.Models.WbsNode", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("ResourceAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
