// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WbsTool.Api.Data;

#nullable disable

namespace WbsTool.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260717125756_AddCompetenciesAndCapacityV1")]
    partial class AddCompetenciesAndCapacityV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("WbsTool.Api.Modules.Capacity.Models.PersonAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PlannedHours")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WbsNodeId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("WbsNodeId");

                    b.ToTable("PersonAllocations", (string)null);
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Capacity.Models.PersonCapacity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AvailableHours")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "WeekStartDate")
                        .IsUnique();

                    b.ToTable("PersonCapacities", (string)null);
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Competencies.Models.Competency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Competencies", (string)null);
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Competencies.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Persons", (string)null);
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Competencies.Models.PersonCompetency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompetencyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompetencyId");

                    b.HasIndex("PersonId", "CompetencyId")
                        .IsUnique();

                    b.ToTable("PersonCompetencies", (string)null);
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Projects.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PlannedEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PlannedStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Wbs.Models.WbsNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ActualHours")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PlannedEnd")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PlannedHours")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PlannedStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsiblePersonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisibleWbsId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProjectId");

                    b.ToTable("WbsNodes", (string)null);
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Capacity.Models.PersonAllocation", b =>
                {
                    b.HasOne("WbsTool.Api.Modules.Competencies.Models.Person", "Person")
                        .WithMany("Allocations")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WbsTool.Api.Modules.Projects.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WbsTool.Api.Modules.Wbs.Models.WbsNode", "WbsNode")
                        .WithMany()
                        .HasForeignKey("WbsNodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Person");

                    b.Navigation("Project");

                    b.Navigation("WbsNode");
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Capacity.Models.PersonCapacity", b =>
                {
                    b.HasOne("WbsTool.Api.Modules.Competencies.Models.Person", "Person")
                        .WithMany("Capacities")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Competencies.Models.PersonCompetency", b =>
                {
                    b.HasOne("WbsTool.Api.Modules.Competencies.Models.Competency", "Competency")
                        .WithMany("PersonCompetencies")
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WbsTool.Api.Modules.Competencies.Models.Person", "Person")
                        .WithMany("PersonCompetencies")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competency");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Wbs.Models.WbsNode", b =>
                {
                    b.HasOne("WbsTool.Api.Modules.Wbs.Models.WbsNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WbsTool.Api.Modules.Projects.Models.Project", "Project")
                        .WithMany("WbsNodes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Competencies.Models.Competency", b =>
                {
                    b.Navigation("PersonCompetencies");
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Competencies.Models.Person", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Capacities");

                    b.Navigation("PersonCompetencies");
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Projects.Models.Project", b =>
                {
                    b.Navigation("WbsNodes");
                });

            modelBuilder.Entity("WbsTool.Api.Modules.Wbs.Models.WbsNode", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
